# Generated by Django 3.1.2 on 2020-12-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nickname',
            field=models.CharField(default='abhi', max_length=50),
        ),
    ]
